export { default as Benefits } from "./Benefits/Benefits"
export { default as CTA } from "./CTA/CTA"
export { default as History } from "./History/History"
export { default as Navbar } from "./Navbar/Navbar"
export { default as Testimonials } from "./Testimonials/Testimonials"
